
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import org.iata.cargo.Vocabulary;

import com.fasterxml.jackson.annotation.JsonProperty;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Types;
import io.swagger.annotations.ApiModelProperty;


/**
 * Booking details - Deprecated, BookingOption should be used instead
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Booking)
@Deprecated
public class Booking
    extends LogisticsObject
    implements Serializable
{

    @Types
    @JsonProperty("@type")
    @ApiModelProperty(allowableValues = Vocabulary.s_c_Booking)
    protected Set<String> types;

    /**
     * Carrier details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_carrier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, min = 1, max = -1)
    })
    @JsonProperty(Vocabulary.s_p_carrier)
    protected Set<Company> carrier;
    /**
     * Reference to the Carrier products included in the offer
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_carrierProductInfo)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_carrierProductInfo)
    protected CarrierProduct carrierProductInfo;
    /**
     * Consignee details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_consignee)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_consignee)
    protected Company consignee;
    /**
     * Freight Forwarder details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_freightForwarder)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, min = 1, max = -1)
    })
    @JsonProperty(Vocabulary.s_p_freightForwarder)
    protected Set<Company> freightForwarder;
    /**
     * Other parties to be notified of the booking evolution
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_notifyParty)
    @JsonProperty(Vocabulary.s_p_notifyParty)
    protected Set<Company> notifyParty;
    /**
     * Price of the Booking (if different from the offer)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_price)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_price)
    protected Price price;
    /**
     * Reference to the Request
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_requestRef)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_requestRef)
    protected Request requestRef;
    /**
     * Routing details of the offer, to be compared with routing preferences of the quote request
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_routing)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_routing)
    protected Routing routing;
    /**
     * Details of the shipement that is to be shipped
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_shipmentDetails)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_shipmentDetails)
    protected Shipment shipmentDetails;
    /**
     * Shipper information
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_shipper)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_shipper)
    protected Company shipper;
    /**
     * Transport segment linked to the offer, including the Departure and Arrival locations
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_transportMovement)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_transportMovement)
    protected TransportSegment transportMovement;
    /**
     * House or Master Waybill unique identifier
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_waybillNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_waybillNumber)
    protected Waybill waybillNumber;
    /**
     * Status of the Booking with regards to the step in the Quote and Book process: Quoted, Booked
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_bookingStatus)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_bookingStatus)
    protected String bookingStatus;
    /**
     * Latest Acceptance time as per CargoIQ definition
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_latestAcceptanceTime)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_latestAcceptanceTime)
    protected Date latestAcceptanceTime;
    /**
     * Indicates if the offer is a perfect match to the quote request (boolean)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_requestMatchInd)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_requestMatchInd)
    protected Boolean requestMatchInd;
    /**
     * Indicate the secruty state of the shipment, screened or not
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_shipmentSecurityStatus)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_shipmentSecurityStatus)
    protected String shipmentSecurityStatus;
    /**
     * Time of availability of the shipment as per CargoIQ definition
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_timeOfAvailability)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_timeOfAvailability)
    protected Date timeOfAvailability;
    /**
     * Total transit time as per CargoIQ definition
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_totalTransitTime)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_totalTransitTime)
    protected String totalTransitTime;

    @Deprecated
    public void setCarrier(Set<Company> carrier) {
        this.carrier = carrier;
    }

    @Deprecated
    public Set<Company> getCarrier() {
        return carrier;
    }

    @Deprecated
    public void setCarrierProductInfo(CarrierProduct carrierProductInfo) {
        this.carrierProductInfo = carrierProductInfo;
    }

    @Deprecated
    public CarrierProduct getCarrierProductInfo() {
        return carrierProductInfo;
    }

    @Deprecated
    public void setConsignee(Company consignee) {
        this.consignee = consignee;
    }

    @Deprecated
    public Company getConsignee() {
        return consignee;
    }

    @Deprecated
    public void setFreightForwarder(Set<Company> freightForwarder) {
        this.freightForwarder = freightForwarder;
    }

    @Deprecated
    public Set<Company> getFreightForwarder() {
        return freightForwarder;
    }

    @Deprecated
    public void setNotifyParty(Set<Company> notifyParty) {
        this.notifyParty = notifyParty;
    }

    @Deprecated
    public Set<Company> getNotifyParty() {
        return notifyParty;
    }

    @Deprecated
    public void setPrice(Price price) {
        this.price = price;
    }

    @Deprecated
    public Price getPrice() {
        return price;
    }

    @Deprecated
    public void setRequestRef(Request requestRef) {
        this.requestRef = requestRef;
    }

    @Deprecated
    public Request getRequestRef() {
        return requestRef;
    }

    @Deprecated
    public void setRouting(Routing routing) {
        this.routing = routing;
    }

    @Deprecated
    public Routing getRouting() {
        return routing;
    }

    @Deprecated
    public void setShipmentDetails(Shipment shipmentDetails) {
        this.shipmentDetails = shipmentDetails;
    }

    @Deprecated
    public Shipment getShipmentDetails() {
        return shipmentDetails;
    }

    @Deprecated
    public void setShipper(Company shipper) {
        this.shipper = shipper;
    }

    @Deprecated
    public Company getShipper() {
        return shipper;
    }

    @Deprecated
    public void setTransportMovement(TransportSegment transportMovement) {
        this.transportMovement = transportMovement;
    }

    @Deprecated
    public TransportSegment getTransportMovement() {
        return transportMovement;
    }

    @Deprecated
    public void setWaybillNumber(Waybill waybillNumber) {
        this.waybillNumber = waybillNumber;
    }

    @Deprecated
    public Waybill getWaybillNumber() {
        return waybillNumber;
    }

    @Deprecated
    public void setBookingStatus(String bookingStatus) {
        this.bookingStatus = bookingStatus;
    }

    @Deprecated
    public String getBookingStatus() {
        return bookingStatus;
    }

    @Deprecated
    public void setLatestAcceptanceTime(Date latestAcceptanceTime) {
        this.latestAcceptanceTime = latestAcceptanceTime;
    }

    @Deprecated
    public Date getLatestAcceptanceTime() {
        return latestAcceptanceTime;
    }

    @Deprecated
    public void setRequestMatchInd(Boolean requestMatchInd) {
        this.requestMatchInd = requestMatchInd;
    }

    @Deprecated
    public Boolean getRequestMatchInd() {
        return requestMatchInd;
    }

    @Deprecated
    public void setShipmentSecurityStatus(String shipmentSecurityStatus) {
        this.shipmentSecurityStatus = shipmentSecurityStatus;
    }

    @Deprecated
    public String getShipmentSecurityStatus() {
        return shipmentSecurityStatus;
    }

    @Deprecated
    public void setTimeOfAvailability(Date timeOfAvailability) {
        this.timeOfAvailability = timeOfAvailability;
    }

    @Deprecated
    public Date getTimeOfAvailability() {
        return timeOfAvailability;
    }

    @Deprecated
    public void setTotalTransitTime(String totalTransitTime) {
        this.totalTransitTime = totalTransitTime;
    }

    @Deprecated
    public String getTotalTransitTime() {
        return totalTransitTime;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

}
