
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import org.iata.cargo.Vocabulary;

import com.fasterxml.jackson.annotation.JsonProperty;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Types;
import io.swagger.annotations.ApiModelProperty;


/**
 * Booking details - Deprecated, BookingOption should be used instead
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Booking)
@Deprecated
public class Booking
    extends LogisticsObject
    implements Serializable
{

    @Types
    @JsonProperty("@type")
    @ApiModelProperty(allowableValues = Vocabulary.s_c_Booking)
    protected Set<String> types;

    /**
     * Details of the shipement that is to be shipped
     *
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_shipmentDetails)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_shipmentDetails)
    protected Shipment shipmentDetails;

    /**
     * Schedule preferences of the request
     *
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_timePreferences)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_timePreferences)
    protected BookingTimes timePreferences;

    /**
     * Unit preferences of the request (e.g. kg or cm)
     *
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_unitsPreference)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_unitsPreference)
    protected Value unitsPreference;

    /**
     * Reference to the Allotment as per the contracts between forwarders and carriers
     *
     */
    @OWLDataProperty(iri = Vocabulary.s_p_allotment)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_allotment)
    protected String allotment;

    /**
     * Expected commodity for quote request purposes only. To be defined by MCD
     *
     */
    @OWLDataProperty(iri = Vocabulary.s_p_expectedCommodities)
    @JsonProperty(Vocabulary.s_p_expectedCommodities)
    protected Set<String> expectedCommodities;
    /**
     * Identification of the request type: Quote or Booking (to be confirmed)
     *
     */
    @OWLDataProperty(iri = Vocabulary.s_p_requestType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_requestType)
    protected String requestType;
    /**
     * Requested handling information for quote request purposes only
     *
     */
    @OWLDataProperty(iri = Vocabulary.s_p_requestedHandling)
    @JsonProperty(Vocabulary.s_p_requestedHandling)
    protected Set<String> requestedHandling;
    /**
     * Indicate the security state of the shipment, screened or not
     *
     */
    @OWLDataProperty(iri = Vocabulary.s_p_shipmentSecurityStatus_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_shipmentSecurityStatus_A)
    protected String shipmentSecurityStatus;


    @Deprecated
    public Set<String> getTypes() {
        return types;
    }

    @Deprecated
    public void setTypes(Set<String> types) {
        this.types = types;
    }

    @Deprecated
    public Shipment getShipmentDetails() {
        return shipmentDetails;
    }

    @Deprecated
    public void setShipmentDetails(Shipment shipmentDetails) {
        this.shipmentDetails = shipmentDetails;
    }

    @Deprecated
    public BookingTimes getTimePreferences() {
        return timePreferences;
    }

    @Deprecated
    public void setTimePreferences(BookingTimes timePreferences) {
        this.timePreferences = timePreferences;
    }

    @Deprecated
    public Value getUnitsPreference() {
        return unitsPreference;
    }

    @Deprecated
    public void setUnitsPreference(Value unitsPreference) {
        this.unitsPreference = unitsPreference;
    }

    @Deprecated
    public String getAllotment() {
        return allotment;
    }

    @Deprecated
    public void setAllotment(String allotment) {
        this.allotment = allotment;
    }

    @Deprecated
    public Set<String> getExpectedCommodities() {
        return expectedCommodities;
    }

    @Deprecated
    public void setExpectedCommodities(Set<String> expectedCommodities) {
        this.expectedCommodities = expectedCommodities;
    }

    @Deprecated
    public String getRequestType() {
        return requestType;
    }

    @Deprecated
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    @Deprecated
    public Set<String> getRequestedHandling() {
        return requestedHandling;
    }

    @Deprecated
    public void setRequestedHandling(Set<String> requestedHandling) {
        this.requestedHandling = requestedHandling;
    }

    @Deprecated
    public String getShipmentSecurityStatus() {
        return shipmentSecurityStatus;
    }

    @Deprecated
    public void setShipmentSecurityStatus(String shipmentSecurityStatus) {
        this.shipmentSecurityStatus = shipmentSecurityStatus;
    }

}
