
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import org.iata.cargo.Vocabulary;

import com.fasterxml.jackson.annotation.JsonProperty;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Types;
import io.swagger.annotations.ApiModelProperty;


/**
 * Booking details
 *
 * This class was generated by OWL2Java 0.17.2
 *
 */
@OWLClass(iri = Vocabulary.s_c_BookingOption)
public class BookingOption
    extends LogisticsObject
    implements Serializable
{

    @Types
    @JsonProperty("@type")
    @ApiModelProperty(allowableValues = Vocabulary.s_c_BookingOption)
    protected Set<String> types;

    /**
     * Booking Segment of the Booking Option
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_bookingSegment)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_bookingSegment)
    protected BookingSegment bookingSegment;
    /**
     * booking times details of the Booking Option (proposed or actual)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_bookingTimes)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_bookingTimes)
    protected BookingTimes bookingTimes;
    /**
     * Carrier details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_carrier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_carrier)
    protected Company carrier;
    /**
     * Reference to the Carrier products included in the offer
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_carrierProductInfo)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_carrierProductInfo)
    protected CarrierProduct carrierProductInfo;
    /**
     * Parties involved in the Booking Option (e.g. shipper, forwarder, ...)
     *
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_parties)
    @JsonProperty(Vocabulary.s_p_parties)
    protected Set<Party> parties;
    /**
     * Price of the Booking (if different from the offer)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_price)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_price)
    protected Price price;
    /**
     * Reference to the Booking option request
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_requestRef)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_requestRef)
    protected BookingOptionRequest requestRef;
    /**
     * Routing details of the offer, to be compared with routing preferences of the quote request
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_routing)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_routing)
    protected Routing routing;
    /**
     * Details of the shipement that is to be shipped
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_shipmentDetails)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_shipmentDetails_A)
    protected Shipment shipmentDetails;
    /**
     * Transport segment linked to the offer, including the Departure and Arrival locations
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_transportMovement)
    @JsonProperty(Vocabulary.s_p_transportMovement)
    protected Set<TransportSegment> transportMovement;
    /**
     * House or Master Waybill unique identifier
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_waybillNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_waybillNumber)
    protected Waybill waybillNumber;
    /**
     * Status of the Booking with regards to the step in the Sales and Booking process: Quoted, Booked (to be confirmed)
     *
     */
    @OWLDataProperty(iri = Vocabulary.s_p_bookingStatus)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_bookingStatus)
    protected String bookingStatus;
    /**
     * Starting datetime of availability of the booking option
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_offerValidFrom)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_offerValidFrom)
    protected Date offerValidFrom;
    /**
     * Ending datetime of availability of the booking option
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_offerValidTo)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_offerValidTo)
    protected Date offerValidTo;
    /**
     * Indicates if the offer is a perfect match to the quote request (boolean)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_requestMatchInd)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_requestMatchInd)
    protected Boolean requestMatchInd;
    /**
     * Indicate the secruty state of the shipment, screened or not
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_shipmentSecurityStatus)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_shipmentSecurityStatus_A)
    protected String shipmentSecurityStatus;

    public void setBookingSegment(BookingSegment bookingSegment) {
        this.bookingSegment = bookingSegment;
    }

    public BookingSegment getBookingSegment() {
        return bookingSegment;
    }

    public void setBookingTimes(BookingTimes bookingTimes) {
        this.bookingTimes = bookingTimes;
    }

    public BookingTimes getBookingTimes() {
        return bookingTimes;
    }

    public void setCarrier(Company carrier) {
        this.carrier = carrier;
    }

    public Company getCarrier() {
        return carrier;
    }

    public void setCarrierProductInfo(CarrierProduct carrierProductInfo) {
        this.carrierProductInfo = carrierProductInfo;
    }

    public CarrierProduct getCarrierProductInfo() {
        return carrierProductInfo;
    }

    public void setParties(Set<Party> parties) {
        this.parties = parties;
    }

    public Set<Party> getParties() {
        return parties;
    }

    public void setPrice(Price price) {
        this.price = price;
    }

    public Price getPrice() {
        return price;
    }

    public void setRequestRef(BookingOptionRequest requestRef) {
        this.requestRef = requestRef;
    }

    public BookingOptionRequest getRequestRef() {
        return requestRef;
    }

    public void setRouting(Routing routing) {
        this.routing = routing;
    }

    public Routing getRouting() {
        return routing;
    }

    public void setShipmentDetails(Shipment shipmentDetails) {
        this.shipmentDetails = shipmentDetails;
    }

    public Shipment getShipmentDetails() {
        return shipmentDetails;
    }

    public void setTransportMovement(Set<TransportSegment> transportMovement) {
        this.transportMovement = transportMovement;
    }

    public Set<TransportSegment> getTransportMovement() {
        return transportMovement;
    }

    public void setWaybillNumber(Waybill waybillNumber) {
        this.waybillNumber = waybillNumber;
    }

    public Waybill getWaybillNumber() {
        return waybillNumber;
    }

    public void setBookingStatus(String bookingStatus) {
        this.bookingStatus = bookingStatus;
    }

    public String getBookingStatus() {
        return bookingStatus;
    }

    public void setOfferValidFrom(Date offerValidFrom) {
        this.offerValidFrom = offerValidFrom;
    }

    public Date getOfferValidFrom() {
        return offerValidFrom;
    }

    public void setOfferValidTo(Date offerValidTo) {
        this.offerValidTo = offerValidTo;
    }

    public Date getOfferValidTo() {
        return offerValidTo;
    }

    public void setRequestMatchInd(Boolean requestMatchInd) {
        this.requestMatchInd = requestMatchInd;
    }

    public Boolean getRequestMatchInd() {
        return requestMatchInd;
    }

    public void setShipmentSecurityStatus(String shipmentSecurityStatus) {
        this.shipmentSecurityStatus = shipmentSecurityStatus;
    }

    public String getShipmentSecurityStatus() {
        return shipmentSecurityStatus;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }
}
