
package org.iata.cargo.model;

import java.io.Serializable;

import org.iata.cargo.Vocabulary;

import com.fasterxml.jackson.annotation.JsonProperty;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Previsouly called Schedule. This object refers to times used for the Booking Option Request (preferences part of the request) or the Booking Option (times sur as LAT where there is a commitment from the carrier)
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_BookingTimes)
public class BookingTimes
    extends LogisticsObject
    implements Serializable
{

    /**
     * Reference to the BookingOption where the booking times are used
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_bookingOption)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_bookingOption)
    protected BookingOption bookingOption;
    /**
     * Reference to the BookingOptionRequest where the booking times are used
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_bookingOptionRequest)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_bookingOptionRequest)
    protected BookingOptionRequest bookingOptionRequest;

    public void setBookingOption(BookingOption bookingOption) {
        this.bookingOption = bookingOption;
    }

    public BookingOption getBookingOption() {
        return bookingOption;
    }

    public void setBookingOptionRequest(BookingOptionRequest bookingOptionRequest) {
        this.bookingOptionRequest = bookingOptionRequest;
    }

    public BookingOptionRequest getBookingOptionRequest() {
        return bookingOptionRequest;
    }

}
