
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;

import io.swagger.annotations.ApiModelProperty;
import org.iata.cargo.Vocabulary;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.kbss.jopa.vocabulary.RDFS;


/**
 * Company branches
 *
 * This class was generated by OWL2Java 0.17.2
 *
 */
@OWLClass(iri = Vocabulary.s_c_CompanyBranch)
public class CompanyBranch
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @JsonIgnore
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @JsonIgnore
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    @JsonProperty("@type")
    @ApiModelProperty(allowableValues = Vocabulary.s_c_CompanyBranch)
    protected Set<String> types;
    @Properties
    @JsonIgnore
    protected Map<String, Set<String>> properties;
    /**
     * Refers to the mother company of the branch
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_company_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_company_A)
    protected Company company;
    /**
     * Contact person details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_contactPersons)
    @JsonProperty(Vocabulary.s_p_contactPersons)
    protected Set<Person> contactPersons;
    /**
     * Location and address details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_location_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_location_A)
    protected Location location;
    /**
     * Other identifiers (e.g. LEI (Legal Entity Identifier), TIN (Trader Identification Number), PIMA address, Account number, VAT/Tax id, Legal Registration id, DUNS number, etc)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherIdentifiers)
    @JsonProperty(Vocabulary.s_p_otherIdentifiers)
    protected Set<OtherIdentifier> otherIdentifiers;
    /**
     * Company branch name
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_branchName)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_branchName)
    protected String branchName;
    /**
     * IATA CASS cargo agent 4 digit branch number / location identifier
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_iataCargoAgentLocationIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_iataCargoAgentLocationIdentifier)
    protected String iataCargoAgentLocationIdentifier;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("CompanyBranch {"+ name)+"<")+ id)+">")+"}");
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Company getCompany() {
        return company;
    }

    public void setContactPersons(Set<Person> contactPersons) {
        this.contactPersons = contactPersons;
    }

    public Set<Person> getContactPersons() {
        return contactPersons;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public Location getLocation() {
        return location;
    }

    public void setOtherIdentifiers(Set<OtherIdentifier> otherIdentifiers) {
        this.otherIdentifiers = otherIdentifiers;
    }

    public Set<OtherIdentifier> getOtherIdentifiers() {
        return otherIdentifiers;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    public String getBranchName() {
        return branchName;
    }

    public void setIataCargoAgentLocationIdentifier(String iataCargoAgentLocationIdentifier) {
        this.iataCargoAgentLocationIdentifier = iataCargoAgentLocationIdentifier;
    }

    public String getIataCargoAgentLocationIdentifier() {
        return iataCargoAgentLocationIdentifier;
    }

}
