
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Set;

import org.iata.cargo.Vocabulary;

import com.fasterxml.jackson.annotation.JsonProperty;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Types;
import io.swagger.annotations.ApiModelProperty;


/**
 * Request object, refers to the Quote request or Booking request 
 *
 * This class was generated by OWL2Java 0.17.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Request)
@Deprecated
public class Request
    extends LogisticsObject
    implements Serializable
{

    @Types
    @JsonProperty("@type")
    @ApiModelProperty(allowableValues = Vocabulary.s_c_Request)
    protected Set<String> types;

    /**
     * Parties involved if known
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_parties_A_A_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_parties_A_A_A)
    protected OtherParty parties;
    /**
     * Ratings preferences of the request
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_ratingsPreference_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_ratingsPreference_A)
    protected Ratings ratingsPreference;
    /**
     * Details of the shipement that is to be shipped
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_shipmentDetails_A_A_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_shipmentDetails_A_A_A)
    protected Shipment shipmentDetails;
    /**
     * Transport segment linked to the request, including the Departure and Arrival locations requested
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_transportMovement_A_A_A_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_transportMovement_A_A_A_A)
    protected TransportSegment transportMovement;
    /**
     * Unit preferences of the request (e.g. kg or cm)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_unitsPreference_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_unitsPreference_A)
    protected Value unitsPreference;

    @Deprecated
    public void setParties(OtherParty parties) {
        this.parties = parties;
    }

    @Deprecated
    public OtherParty getParties() {
        return parties;
    }

    @Deprecated
    public void setRatingsPreference(Ratings ratingsPreference) {
        this.ratingsPreference = ratingsPreference;
    }

    @Deprecated
    public Ratings getRatingsPreference() {
        return ratingsPreference;
    }

    @Deprecated
    public void setShipmentDetails(Shipment shipmentDetails) {
        this.shipmentDetails = shipmentDetails;
    }

    @Deprecated
    public Shipment getShipmentDetails() {
        return shipmentDetails;
    }

    @Deprecated
    public void setTransportMovement(TransportSegment transportMovement) {
        this.transportMovement = transportMovement;
    }

    @Deprecated
    public TransportSegment getTransportMovement() {
        return transportMovement;
    }

    @Deprecated
    public void setUnitsPreference(Value unitsPreference) {
        this.unitsPreference = unitsPreference;
    }

    @Deprecated
    public Value getUnitsPreference() {
        return unitsPreference;
    }

    @Deprecated
    public Set<String> getTypes() {
        return types;
    }

    @Deprecated
    public void setTypes(Set<String> types) {
        this.types = types;
    }

}
