name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_PACKAGES_ACCESS_USER: ${{ secrets.GH_PACKAGES_ACCESS_USER }}
  GITHUB_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK with Dependency Caching
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          cache: 'gradle'

      - name: Get tag version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Create release artifacts
        run: ./gradlew -Pversion=${{ steps.get_version.outputs.version-without-v }} jar sourcesJar

      - name: Release without Changelog
        uses: softprops/action-gh-release@v1
        with:
          name: ONE.Record Ontology-Model Library ${{ steps.get_version.outputs.version-without-v }}
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish artifacts to GitHub Packages
        run: |
          echo "New version: ${{ steps.get_version.outputs.version-without-v }}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${{ steps.get_version.outputs.version-without-v }} publish
        env:
          PROJECT_URL: ${{ github.event.repository.url }}
          MAVEN_PUBLISH_URL: https://maven.pkg.github.com/${{ github.repository }}
          MAVEN_PUBLISH_USERNAME: ${{ github.actor }}
          MAVEN_PUBLISH_PASSWORD: ${{ github.token }}
